"""Reproduce the mlearn generation gate for the Long tail card attempt."""
import json, sys
from pathlib import Path

sys.path.insert(0, "/Users/danielwallner/dev/mlearn")
from mlearn import infographic as imod
from mlearn import validate as vmod
from mlearn import visualqa as vqa
from mlearn.infographic import render_spec

CARD = {
    "title": "Long Tail: When Niches Outsell the Hits",
    "hook": "The internet flipped retail economics: with near-zero storage and delivery costs, thousands of niche products that each sell only a little can together outsell the few blockbusters. That is the long tail \u2014 selling less of more.",
    "body_md": "*The long tail is the insight that when storage and delivery become nearly free, thousands of niche products that each sell only a little can, together, outsell the few blockbusters.*\n\n### What the long tail means\nProduct demand rarely follows a bell curve. It follows a **power law**: very few products are hits, and very many sell a little. The hits form the **head** of the demand curve; all the small sellers form the **long tail**. In business, the long tail is the total sales of these \"non-hit\" items.\n\nOld shops could only serve the head, because shelves cost money. The internet made serving the tail viable.\n\n| | Head | Long tail |\n|---|---|---|\n| Products | few, very popular | millions of niches |\n| Sales per item | huge | small |\n| Cost to stock | high in shops | near zero online |\n| Total revenue | large | rivals the head together |\n\n### The mechanism: three parts\n1. **Supply**: near-zero storage and distribution costs, like central warehouses and digital catalogs.\n2. **Discovery**: search and recommendations help fans find obscure products.\n3. **Aggregation**: millions of small sales add up to one big total.\n\n```mermaid\nflowchart LR\n    A[Storage nearly free] -->|stock every niche| B[Millions of rare items]\n    B -->|fans find them| C[Small sales each]\n    C -->|add up| D[Tail rivals the hits]\n```\n\n### A story that made it famous\nThe climbing book *Touching the Void* got good reviews but sold little. When *Into Thin Air* became a hit years later, Amazon's recommendations revived the older book. Fans of one wanted the other. An Amazon employee said: \"We sold more books today that didn't sell at all yesterday than we sold today of all the books that did sell yesterday.\"\n\n### Evidence from the numbers\nEconomists Brynjolfsson, Hu and Smith studied Amazon for years. Their 2003 finding: product variety gives consumers **ten times** more value than lower prices. By 2008, niche books made up **36.7%** of Amazon's sales. Consumer value from niche books grew at least **fivefold** from 2000 to 2008. Sales are also less concentrated online: the **80/20** rule fits the catalog channel, while the internet fits a **72/28** rule.\n\n### One warning\n\"Long tail\" also has a statistical meaning. In the Gutenberg-Richter law, the tail holds rare, giant earthquakes, and those extremes dominate. That is the opposite of Anderson's business idea, where many small sellers add up. Do not mix the two.",
    "diagram_type": "data",
    "diagram_src": "",
    "infographic_spec": "infographic list-row-horizontal-icon-arrow\ndata\n  title How the long tail pays off\n  lists\n    - label Storage near zero\n      desc Warehouses and digital catalogs make niche items viable\n      icon banknote\n    - label Stock every niche\n      desc List rare books and films, not just proven hits\n      icon book\n    - label Fans find them\n      desc Search and recommendations surface obscure products\n      icon users\n    - label Tail rivals hits\n      desc Small sales add up to blockbuster-size revenue\n      icon chart line\ntheme\n  palette #22d3ee #22c55e #f59e0b #eab308",
    "infographic_svg": None,
    "figures": [
        {"value": 36.7, "source": "by 2008, niche books accounted for 36.7% of Amazon's sales"},
        {"value": 10, "source": "is ten times larger than their benefit from access to lower prices online"},
        {"value": 5, "source": "the consumer surplus generated by niche books has increased at least fivefold from 2000 to 2008"},
        {"value": 80, "source": "An 80/20 rule fits the distribution of product sales in the catalog channel quite well"},
        {"value": 72, "source": "this rule needs to be modified to a 72/28 rule in order to fit the distribution of product sales in that channel"},
    ],
    "anchor_quote": "We sold more books today that didn't sell at all yesterday than we sold today of all the books that did sell yesterday.",
    "prompts": [
        {"question": "What exactly is the 'long tail' in business?", "answer": "It is the total sales of all the niche products that each sell only a little. Together they can rival or exceed the few blockbuster hits."},
        {"question": "Which supply-side and demand-side conditions make a long-tail market possible?", "answer": "Supply side: near-zero storage and distribution costs. Demand side: search and recommendations so customers find niche products. Enough choice and a large population help too."},
        {"question": "Why did the sales rule shift from 80/20 in catalogs to 72/28 on the internet?", "answer": "The internet lowers search and distribution costs, so sales concentrate less on hits \u2014 obscure products take a bigger share online."},
        {"question": "How does the statistical long tail of the Gutenberg-Richter law differ from the business long tail?", "answer": "In statistics the tail means rare extreme events, like giant earthquakes, that dominate. In business it means millions of small sellers whose sales add up. The two are opposite phenomena."},
    ],
}

tools = Path("/Users/danielwallner/dev/mlearn/tools")
raw = Path("/Users/danielwallner/dev/mlearn/data/raw/c527abe72f4aabc5.html")
source_body = raw.read_text(errors="replace")

# Replay the generate pipeline: parse -> add keys -> lane -> validate
card = dict(CARD)
card["cluster"] = "innovation"
card["source_url"] = "https://en.wikipedia.org/wiki/Long_tail"
card["figures_json"] = json.dumps(card.get("figures") or [])

print("=== lane: spec_valid ===")
ok, err = imod.spec_valid(card["infographic_spec"])
print("spec_valid:", ok, err)

print("=== lane: render ===")
svg, rerr = render_spec(card["infographic_spec"], tools)
if svg:
    Path("/tmp/longtail_banner.svg").write_text(svg)
    print("render: OK -> /tmp/longtail_banner.svg (%d bytes)" % len(svg))
else:
    print("render: FAILED:", rerr)

if svg:
    print("=== lane: visual QA ===")
    ok, verr = vqa.qa_banner_svg(svg)
    print("qa_banner_svg:", ok, verr)
    print("=== truncation probe ===")
    trunc = imod._check_truncation(card["infographic_spec"], svg)
    print("truncation:", trunc)
    print("palette:", imod._check_palette(card["infographic_spec"]))
    print("liveliness:", imod._check_liveliness(card["infographic_spec"], svg))

print("=== full validate_card (as generate does) ===")
if svg:
    card["infographic_svg"] = svg
    card["_infographic_lane"] = "antv"
ok, errors = vmod.validate_card(card, source_body, tools, infographic_strict=False)
print("validate ok:", ok)
for e in errors:
    print(" ERROR:", e)